[package]
name = "cosmic-nom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
nom-supreme = "0.6.0"
nom_locate = "4.0.0"
serde = { version="1.0.69", features=['derive','rc'] }
