[package]
name = "cosmic-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
mesh-portal = { path="../mesh-portal", default-features=false}
mesh-portal-versions = { path="../mesh-portal-versions", default-features=false}
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
strum = "0.21.0"
strum_macros = "0.21.1"
regex = "1.5.4"
nom = "7"
nom-supreme = "0.6.0"
nom_locate = "4.0.0"
serde = "1.0.79"
chrono = { version="0.4.19", features=["serde"] }
